spring:
  application:
    name: coinone-mcp
  threads:
    virtual:
      enabled: true

  main:
    web-application-type: none
    banner-mode: off
server:
  port: 8080

logging:
  level:
    root: error
    kr.co.coinone: error
  pattern:
    console: ""

# MCP Server Configuration
mcp:
  server:
    enabled: true
